[package]
name = "odf_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.21"
syn = { version = "1.0.103", features = ["full", "parsing"] }
proc-macro2 = "1.0"
darling = "0.14.2"
trybuild = "1.0.71"
convert_case = "0.6.0"
